#!/usr/bin/python

import sys
import hashlib

if len(sys.argv) < 2:
	print >>sys.stderr, "Usage: %s <uniqname1> <uniqname2> ..." % sys.argv[0]
	sys.exit(1)

with open("cookie", "w") as file:
	print >>file, int(hashlib.sha1('|'.join(sorted(sys.argv[1:]))).hexdigest(),16) % 0x8FFF,
